CREATE TABLE IF NOT EXISTS `composition_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `template_code` varchar(50) NOT NULL,
  `template_name` varchar(255) NOT NULL,
  `installation_method_id` int(11) DEFAULT NULL,
  `trade_id` int(11) DEFAULT NULL,
  `phase_id` int(11) DEFAULT NULL,
  `system_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `template_code` (`template_code`),
  CONSTRAINT `fk_composition_templates_method` FOREIGN KEY (`installation_method_id`) REFERENCES `installation_methods` (`installation_method_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_composition_templates_trade` FOREIGN KEY (`trade_id`) REFERENCES `project_trades` (`trade_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_composition_templates_phase` FOREIGN KEY (`phase_id`) REFERENCES `project_work_phases` (`phase_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_composition_templates_system` FOREIGN KEY (`system_id`) REFERENCES `project_systems` (`system_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `composition_template_details` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `template_id` int(11) NOT NULL,
  `detail_type` ENUM('MATERIAL', 'LABOR') DEFAULT 'MATERIAL',
  `inventory_item_id` int(11) DEFAULT NULL,
  `seq` int(11) NOT NULL DEFAULT 0,
  `description` varchar(255) DEFAULT NULL,
  `qty_formula` text DEFAULT NULL,
  `waste_percentage` decimal(10,2) DEFAULT 0.00,
  `remarks` text DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `hours` decimal(10,2) DEFAULT 0.00,
  `rate` decimal(10,2) DEFAULT 0.00,
  `formula` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `template_id` (`template_id`),
  CONSTRAINT `composition_template_details_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `composition_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
